config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :todos do
    member do
      post :done
    end
  end
  root 'todos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates_presence_of :name, :due_date, :note

  def done?
    !overdue?
  end

  private

  def overdue?
    due_date < Date.today
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  before_action :find_todo, only: [:show, :edit, :update, :destroy, :done]

  def index
    @todos = Todo.order(due_date: :asc)  
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      flash[:notice] = 'Success'
      redirect_to todos_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @todo.update_attributes(todo_params)
      redirect_to todo_path(@todo)
    else
      render :edit
    end
  end

  def destroy
    @todo.destroy

    redirect_to todos_path
  end

  def done
    @todo.update(done: !(@todo.done))
  end

  private

  def find_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:name, :due_date, :note, :done)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper

  def todo_show_button(todo)
    link_to 'Show', todo_path(todo), class: 'btn btn-info'
  end

  def todo_delete_button(todo)
    return unless todo.done?
    link_to 'Delete', todo_path(todo), class: 'btn btn-danger', method: :delete, data: { confirm: 'Delete this item ?' }
  end

  def todo_edit_button(todo)
    link_to 'Edit', edit_todo_path(todo), class: 'btn btn-primary'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<div class="form container">

  <div class="errorbox">
    <% if @todo.errors.any? %>
      <ul class="errorlist">
        <% @todo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="itembox">
    <%= form_for @todo do |f| %>

      <div class="form group">
        <%= f.label :name, "Name" %>
        <br>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <br>
      <div class="form group">
        <%= f.label :due_date, "Due Date" %>
        <br>
        <%= f.date_select :due_date, class: "form-control" %>
      </div>
      <br>
      <div class="form group">
        <%= f.label :note, "Note" %>
        <br>
        <%= f.text_area :note, class: "form-control" %>
      </div>
      <br>
      <%= f.submit "Submit", class: "btn btn-success" %>
      <%= link_to 'BACK', :back, class: 'btn btn-default' %>
    <% end %>  
  </div>

</div>

app/views/todos/edit.html.erb
<%= render "form" %>

app/views/todos/index.html.erb
<div class="container">

  <h1 class="text-center">Things To Be Done!</h1>

  <div class="addbtn">
    <%= link_to 'New Item', new_todo_path, class: 'btn btn-success' %>
  </div>

  <table class="table table-striped">
    
    <thead>
      <tr>
        <th>Done</th>
        <th>Name</th>
        <th>Due Date</th>
      </tr>
    </thead>
    
    <tbody>

      <% @todos.each do |todo| %>
        <tr>
          <td><%= check_box_tag :done, true, todo.done, data: { url: done_todo_path(todo), method: :post, remote: true } %></td>
          <td><%= todo.name %></td>
          <td><%= todo.due_date %></td>
          <td><%= todo_show_button(todo) %></td>
          <td><%= todo_edit_button(todo) %></td>
          <td><%= todo_delete_button(todo) %></td>
        </tr>
      <% end %>  

    </tbody>

  </table>  

</div>

app/views/todos/new.html.erb
<%= render "form" %>

app/views/todos/show.html.erb
<div class="container">
  <div class="text-center">
    <%= @todo.name %>
    <br>
    <%= @todo.due_date %>
    <br>
    <%= @todo.note %>
    <br>
    <div class="itembox_btn">
      <%= todo_edit_button(@todo) %>
      <%= link_to 'Back', todos_path, class: 'btn btn-default' %>
    </div>
  </div>
</div>